
services:
#DB and cache layer
  cache:
    image: redis:alpine
    container_name: planted-redis
    ports:
      - "6379:6379"
    networks:
      - flora-network

#database layer
  database:
    image: postgres:16
    container_name: "planted-db"
    environment:
      POSTGRES_USER: kitsu
      POSTGRES_PASSWORD: kitsu.postgres.735
      POSTGRES_DB: planted-appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flora-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitsu -d planted-appdb"]
      interval: 5s
      timeout: 40s
      retries: 5

#backend for frontend layer
  bff:
    build:
      context: .
      dockerfile: Dockerfile
      target: bff
    command: npm run dev
    container_name: planted-bff
    ports:
      - "3001:3001"
    env_file:
      - ./bff/.env.development
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_healthy
    networks:
      - flora-network
    volumes:
      - ./bff/src:/app/bff/src
      - ./packages:/app/packages

#forntend layer
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: planted-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    depends_on:
      - bff
    stdin_open: true
    networks:
      - flora-network
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./packages:/app/packages
volumes:
  postgres_data:
networks:
  flora-network:
    driver: bridge